-- ============================================================
-- Snowflake MCP Banking Agent — Teardown / Cleanup
-- Author: Satish Kumar
-- LinkedIn: https://www.linkedin.com/in/satishkumar-snowflake/
-- Medium:   https://medium.com/@snowflakechronicles
-- ============================================================
-- Run in order — suspending tasks must happen before DROP.
-- Replace SATISH with your Snowflake username.
-- ============================================================

-- Step 1: Suspend tasks before dropping
ALTER TASK MCP_DEMO_DB.MCP_SCHEMA.TASK_DAILY_MONITORING_REPORT SUSPEND;
ALTER TASK MCP_DEMO_DB.MCP_SCHEMA.TASK_WEEKLY_MONITORING_REPORT SUSPEND;

-- Step 2: Drop tasks & automation
DROP TASK IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.TASK_DAILY_MONITORING_REPORT;
DROP TASK IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.TASK_WEEKLY_MONITORING_REPORT;
DROP PROCEDURE IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.SP_AGENT_MONITORING_REPORT(FLOAT);
DROP TABLE IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.AGENT_MONITORING_SNAPSHOTS;

-- Step 3: Auth & tokens
ALTER USER SATISH DROP PROGRAMMATIC ACCESS TOKEN mcp_test_token;
ALTER USER SATISH UNSET AUTHENTICATION POLICY;
DROP AUTHENTICATION POLICY IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.MCP_PAT_AUTH_POLICY;
DROP SECURITY INTEGRATION IF EXISTS MCP_OAUTH_INTEGRATION;

-- Step 4: Agents & servers (reverse dependency order)
DROP AGENT IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.BANKING_ASSISTANT;
DROP MCP SERVER IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.MCP_BANKING_SERVER;
DROP SEMANTIC VIEW IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.REVENUE_SEMANTIC_VIEW;
DROP CORTEX SEARCH SERVICE IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.PRODUCT_SEARCH_SERVICE;
DROP FUNCTION IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.CALCULATE_COMPOUND_INTEREST(FLOAT, FLOAT, FLOAT);
DROP FUNCTION IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.CLASSIFY_CUSTOMER_RISK(FLOAT, FLOAT, FLOAT);
DROP TABLE IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.PRODUCTS;
DROP TABLE IF EXISTS MCP_DEMO_DB.MCP_SCHEMA.REVENUE;

-- Step 5: Role, schema, database
DROP ROLE IF EXISTS MCP_CONSUMER_ROLE;
DROP SCHEMA IF EXISTS MCP_DEMO_DB.MCP_SCHEMA;
DROP DATABASE IF EXISTS MCP_DEMO_DB;
